// Generated by CoffeeScript 1.6.3
(function() {
  define(['Playground', 'jquery'], function(Playground) {
    var Player;
    return Player = (function() {
      function Player() {
        this.playground = new Playground;
      }

      Player.prototype.scream = function() {
        this.$el.text('waaaaaaaaaaaa');
        return this;
      };

      Player.prototype.render = function() {
        this.$el = $('<div class="zombie"></div>');
        this.playground.add(this.$el);
        return this;
      };

      return Player;

    })();
  });

}).call(this);
