// Generated by CoffeeScript 1.6.3
(function() {
  define(['jquery'], function() {
    var Playground;
    return Playground = (function() {
      function Playground() {
        this.$el = $('.playground');
      }

      Playground.prototype.add = function(el) {
        return this.$el.append(el);
      };

      return Playground;

    })();
  });

}).call(this);
