// Generated by CoffeeScript 1.6.3
(function() {
  define(['Playground', 'jquery'], function(Playground) {
    var Zombie;
    return Zombie = (function() {
      function Zombie() {
        this.playground = new Playground;
      }

      Zombie.prototype.moan = function() {
        this.$el.text('uuuuuaaaarrr');
        return this;
      };

      Zombie.prototype.render = function() {
        this.$el = $('<div class="zombie"></div>');
        this.playground.add(this.$el);
        return this;
      };

      return Zombie;

    })();
  });

}).call(this);
