// Generated by CoffeeScript 1.6.3
(function() {
  define(['Player'], function(Player) {
    return function() {
      return describe('Player test', function() {
        var player;
        player = null;
        beforeEach(function() {
          return player = new Player;
        });
        it('renders', function() {
          expect(player.$el).toBeUndefined();
          player.render();
          return expect(player.$el).toBeDefined();
        });
        return it('screams', function() {
          player.render();
          expect(player.$el.html()).toEqual('');
          player.scream();
          return expect(player.$el.html()).toEqual('waaaaaaaaaaaa');
        });
      });
    };
  });

}).call(this);
