// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    return [
      {
        path: 'Player',
        defineModules: {
          'Playground': function() {
            return define('Playground', function() {
              var FakePlayground;
              return FakePlayground = (function() {
                function FakePlayground() {}

                FakePlayground.prototype.add = function() {
                  return console.log("mocked playground->add for Player has been called");
                };

                return FakePlayground;

              })();
            });
          }
        }
      }, {
        path: 'Zombie',
        defineModules: {
          'Playground': function() {
            return define('Playground', function() {
              var FakePlayground;
              return FakePlayground = (function() {
                function FakePlayground() {}

                FakePlayground.prototype.add = function() {
                  return console.log("mocked playground->add for Zombie has been called");
                };

                return FakePlayground;

              })();
            });
          }
        }
      }
    ];
  });

}).call(this);
