// Generated by CoffeeScript 1.6.3
(function() {
  define(['Zombie'], function(Zombie) {
    return function() {
      return describe('Zombie test', function() {
        var zombie;
        zombie = null;
        beforeEach(function() {
          return zombie = new Zombie;
        });
        it('renders', function() {
          expect(zombie.$el).toBeUndefined();
          zombie.render();
          return expect(zombie.$el).toBeDefined();
        });
        return it('moans', function() {
          zombie.render();
          expect(zombie.$el.html()).toEqual('');
          zombie.moan();
          return expect(zombie.$el.html()).toEqual('uuuuuaaaarrr');
        });
      });
    };
  });

}).call(this);
